apiVersion: v1
kind: Pod
metadata:
  name: non-prod
  namespace: "177135-prod"
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: "artifactory.com/docker-anonymous/gdat/46142/jnlp-slave:1.0"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "250m"
          memory: "0.75Gi"
        requests:
          cpu: "250m"
          memory: "0.75Gi"
    - name: npm
      image: "artifactory.com/docker-anonymous/gdat/46142/node-ubuntu18:14.18.0"
      imagePullPolicy: IfNotPresent
      tty: true
      resources:
        limits:
          cpu: "1000m"
          memory: "32Gi"
        requests:
          cpu: "1000m"
          memory: "32Gi"
